#!/bin/sh

source GoboPath

cmd="$1"
[ "$cmd" ] || cmd=Start

case "$cmd" in

[Ss]tart)

   mount -t tmpfs tmpfs $goboDevices
   cp -a -f /lib/udev/devices/* $goboDevices
   mount -t devpts devpts $goboDevices/pts

   # udevd listens for hotplug events through netlink
   $goboExecutables/udevd --daemon
   echo "" > "$goboStatus/sys/kernel/hotplug"

   # create a dummy queue entry and create a list of uevents
   mkdir -p $goboDevices/.udev/queue

   list="$(echo $goboObjects/bus/*/devices/*/uevent)"
   list="$list $(echo $goboObjects/class/*/*/uevent)"
   list="$list $(echo $goboObjects/block/*/uevent)"
   list="$list $(echo $goboObjects/block/*/*/uevent)"

   # sort the list
   for i in $list; do
        case "$i" in
            */device/uevent)
                continue
                ;;
            */class/mem/*|*/class/tty/*)
                first="$first $i"
                ;;
            */block/md*)
                last="$last $i"
                ;;
            */*)
                default="$default $i"
                ;;
        esac
   done

   # trigger the sorted events
   for i in $first $default $last; do
      echo "add" > "$i"
   done

   # wait for events to finish
   udevtrigger
   udevsettle --timeout=10

   ;;
   
[Ss]top)

   killall udevd

   ;;
   
[Rr]estart)

   cp -a -f /lib/udev/devices/* $goboDevices
   udevtrigger
   udevsettle --timeout=10

   ;;

esac
