--- vsftpd-2.0.3/Makefile	2005-03-11 20:34:15.000000000 +0100
+++ vsftpd-2.0.3/Makefile.new	2005-04-23 23:32:28.000000000 +0200
@@ -24,21 +24,11 @@
 	$(CC) -o vsftpd $(OBJS) $(LINK) $(LIBS)
 
 install:
-	if [ -x /usr/local/sbin ]; then \
-		$(INSTALL) -m 755 vsftpd /usr/local/sbin/vsftpd; \
-	else \
-		$(INSTALL) -m 755 vsftpd /usr/sbin/vsftpd; fi
-	if [ -x /usr/local/man ]; then \
-		$(INSTALL) -m 644 vsftpd.8 /usr/local/man/man8/vsftpd.8; \
-		$(INSTALL) -m 644 vsftpd.conf.5 /usr/local/man/man5/vsftpd.conf.5; \
-	elif [ -x /usr/share/man ]; then \
-		$(INSTALL) -m 644 vsftpd.8 /usr/share/man/man8/vsftpd.8; \
-		$(INSTALL) -m 644 vsftpd.conf.5 /usr/share/man/man5/vsftpd.conf.5; \
-	else \
-		$(INSTALL) -m 644 vsftpd.8 /usr/man/man8/vsftpd.8; \
-		$(INSTALL) -m 644 vsftpd.conf.5 /usr/man/man5/vsftpd.conf.5; fi
-	if [ -x /etc/xinetd.d ]; then \
-		$(INSTALL) -m 644 xinetd.d/vsftpd /etc/xinetd.d/vsftpd; fi
+		$(INSTALL) -m 755 vsftpd $(DESTDIR)/sbin/vsftpd
+		$(INSTALL) -m 644 vsftpd.8 $(DESTDIR)/man/man8/vsftpd.8
+		$(INSTALL) -m 644 vsftpd.conf.5 $(DESTDIR)/man/man5/vsftpd.conf.5
+#	if [ -x /etc/xinetd.d ]; then \
+#		$(INSTALL) -m 644 xinetd.d/vsftpd /etc/xinetd.d/vsftpd; fi
 
 clean:
 	rm -f *.o *.swp vsftpd
