#!/bin/sh

source GoboPath
#
# Task to store and restore alsa volume settings
# Created by Jonas Karlsson <jonka750@student.liu.se> Tue Nov 14 14:17
#
mkdir -p "$goboVariable/lib/alsa"
case "$1" in
[sS]tart) option="restore" ;;
[sS]top) option="store" ;;
esac # hmm...
alsactl $option

