#!/bin/sh

. ScriptFunctions
Import GoboLinux
Import Log

post_install() {
   local kernelrelease=$(cat include/config/kernel.release)
   private__check_firmware

   mkdir -p $target/bin
   cp "$archsubdir"/WriteBoot64 $target/bin

   if Ask "Do you want to regenerate your UEFI boot application?"
   then $target/bin/WriteBoot64 "$version" "$kernelrelease"
   else Log_Normal "You may regenerate it later on by running \"$target/bin/WriteBoot64 $version $kernelrelease\""
   fi
}

private__copy_kernel_image() {
   local kernelrelease="$1"

   # Copy and symlink kernel and System.map
   dest=$target/Resources/Unmanaged/$goboBoot
   mkdir -p $dest
   cp arch/x86_64/boot/bzImage $dest/kernel-${kernelrelease}
   cp System.map $dest/System.map-${kernelrelease}
 
   ln -fs kernel-${kernelrelease} $dest/kernel
   ln -fs System.map-${kernelrelease} $dest/System.map
}

private__check_firmware () {
   # check for different versions of firmware
   private__check_firmware_version IPW2200 3.0
   private__check_firmware_version IPW2100 1.3
   private__check_firmware_version IWL3945 2.14
   private__check_firmware_version IWL4965 4.44
}

private__check_firmware_version () {
   driver=$1
   req_version=$2
   version_found=false
   if [ -n "`egrep 'CONFIG_${driver}=[my]' .config`" ]
   then
      for version in ${goboPrograms}/${driver}-Firmware/*
      do
         if [ `GuessLatest ${req_version} $version` = `echo $version | sed 's/.*\/\(.*\)$/\1/g'` ]
         then
            version_found=true
            break
         fi
      done 2> /dev/null
      if [ "$version_found" = "false" ]
      then
         Ask "You need to install firmware for the ${driver} driver to work. Do you want to install it?" && InstallPackage ${driver}-Firmware
      fi
   fi
}
