#!/bin/bash
#
# messagebus:   The D-BUS systemwide message bus
#
# chkconfig: 345 97 03
# description:  This is a daemon which broadcasts notifications of system events \
#               and other messages. See http://www.freedesktop.org/software/dbus/
#
# processname: dbus-daemon
# pidfile: /Programs/DBus/Variable/run/dbus/pid
#

source GoboPath

op="$1"
[ "$op" ] || op="start"

function SuperUserWorkaround() {
   if [ "$(SuperUserName)" != "root" ]
   then
      GrepReplace -B "\"root\"" "\"$(SuperUserName)\"" "$goboSettings/dbus-1/system.d"/*.conf
      GrepReplace -B "User=root" "User=$(SuperUserName)" "$goboShared/dbus-1/system-services"/*.service
   fi
}

case "$op" in
[Ss]tart)
   # Sanity checks.
   mkdir -p /System/Variable/run/dbus/
   if [ -e /System/Variable/run/dbus/pid ]
   then
      if ps `cat /System/Variable/run/dbus/pid` &> /dev/null
      then
         echo "Already running."
         exit 1
      else
         rm -f /System/Variable/run/dbus/pid
      fi
   fi   
   # so we can rearrange this easily
   RETVAL=0
   
   SuperUserWorkaround
   /bin/dbus-uuidgen --ensure
   /bin/dbus-daemon --system
   RETVAL=$?
   #sleep 2
   exit $RETVAL
   ;;
[Ss]top)
   killall dbus-daemon
   rm -f /System/Variable/run/dbus/pid > /dev/null
   ;;
esac
