#!/bin/bash -u

# source GoboPath, just in case somebody wants to launch this script from the shell
source GoboPath

mkdir -p $goboVariable/lib/xml

# Create (or update) the $goboVariable/lib/xml/docbook catalog file 
if [ ! -e $goboVariable/lib/xml/docbook ]; then
    xmlcatalog --noout --create $goboVariable/lib/xml/docbook
fi

# Create (or update) the $goboVariable/lib/xml/catalog catalog file
if [ ! -e $goboVariable/lib/xml/catalog ]; then
    xmlcatalog --noout --create $goboVariable/lib/xml/catalog
fi

# Update the catalog files
xmlcatalogdata=$(dirname $(readlink -f $0))/XmlCatalogData
cat "$xmlcatalogdata" | sed -e 's,${target},/usr,g' -e "s,\${goboVariable},$goboVariable,g" | while read line
do
  entrytype=$(echo "$line" | cut -d\; -f1)
  entryorig=$(echo "$line" | cut -d\; -f2)
  entryreplace=$(echo "$line" | cut -d\; -f3)
  catalogfile=$(echo "$line" | cut -d\; -f4)
  xmlcatalog --noout --add "$entrytype" "$entryorig" "$entryreplace" "$catalogfile"
done
