#!/bin/sh
# by Maglan C. Diemer, maglan@univates.br

PGDATA=/Data/Variable/PostgreSQL/data
PGLOGFILE=$PGDATA/postgresql.log

case "$1" in
[Ss]tart)
  cd /
  sudo -u postgres /bin/pg_ctl start -D $PGDATA -l $PGLOGFILE
  ;;
[Ss]top)
  cd /
  sudo -u postgres /bin/pg_ctl stop -D $PGDATA
  ;;
esac
